-- Add Revolut, Wise, N26 as new online-bank entries in document_guides
-- (category = 'финансы'), matching the schema and field set of the
-- existing 15 banks, including full translations (en/uz/tr/tg/uk).
-- Researched and verified September 2026 -- see bank-account-opening-research.md
-- project doc for sources. Run in Supabase SQL Editor.

insert into public.document_guides
  (name, description, when_to_get, where_to_submit, working_hours, online_booking, required_docs, cost, waiting_time, instructions, common_mistakes, tips, links, important_2026, category, type, online_url, tags, price_label, name_en, description_en, where_to_submit_en, working_hours_en, online_booking_en, cost_en, waiting_time_en, important_2026_en, category_en, price_label_en, required_docs_en, instructions_en, common_mistakes_en, tips_en, name_uz, description_uz, where_to_submit_uz, working_hours_uz, online_booking_uz, cost_uz, waiting_time_uz, important_2026_uz, category_uz, price_label_uz, required_docs_uz, instructions_uz, common_mistakes_uz, tips_uz, name_tr, description_tr, where_to_submit_tr, working_hours_tr, online_booking_tr, cost_tr, waiting_time_tr, important_2026_tr, category_tr, price_label_tr, required_docs_tr, instructions_tr, common_mistakes_tr, tips_tr, name_tg, description_tg, where_to_submit_tg, working_hours_tg, online_booking_tg, cost_tg, waiting_time_tg, important_2026_tg, category_tg, price_label_tg, required_docs_tg, instructions_tg, common_mistakes_tg, tips_tg, name_uk, description_uk, where_to_submit_uk, working_hours_uk, online_booking_uk, cost_uk, waiting_time_uk, important_2026_uk, category_uk, price_label_uk, required_docs_uk, instructions_uk, common_mistakes_uk, tips_uk)
values
  ('Revolut',
   'Финтех-необанк, основан в 2015 году в Лондоне. Работает без единого физического отделения, полностью через приложение — оформление счёта занимает несколько минут. Свыше 70 млн клиентов по всему миру, мультивалютный счёт и карта Visa/Mastercard с обменом валют по межбанковскому курсу.',
   NULL,
   'Только через мобильное приложение Revolut (iOS/Android) или сайт revolut.com — офисов и отделений банка в Польше нет.',
   NULL,
   NULL,
   '["Паспорт или ID-карта гражданина ЕС/Великобритании/Швейцарии (действительны минимум 1 месяц)", "Для граждан других стран — дополнительно виза или карта побыту (действительны минимум 3 месяца)", "Для украинцев — карта побыту, виза, польский документ иностранца или разрешение на толерованное пребывание", "Селфи для видеоверификации в приложении — PESEL не требуется"]'::jsonb,
   'План Standard — 0 zł. Платные планы: Plus — 19,99 zł/мес, Premium — 33,99 zł/мес, Metal — 55,99 zł/мес, Ultra — от 260 zł/мес (вводная цена).',
   'Регистрация — несколько минут, проверка документов может занимать до 5 рабочих дней.',
   '["Скачайте приложение Revolut и зарегистрируйтесь по номеру телефона", "Сфотографируйте паспорт или ID-карту и пройдите видеоселфи-верификацию", "Укажите адрес проживания в Польше", "Получите виртуальную карту сразу в приложении, физическую — закажите отдельно с доставкой по почте"]'::jsonb,
   '["Пытаться открыть счёт по туристической визе или студенческому виду на жительство без дополнительных документов — Revolut может их не принять"]'::jsonb,
   '["Один из самых популярных финтех-банков в Европе — свыше 70 млн клиентов по всему миру", "Мультивалютный счёт и карта Visa/Mastercard с обменом валют по выгодному курсу", "Бесплатный план ограничивает снятие наличных и обмен валют без комиссии — при активном использовании платный план может быть выгоднее"]'::jsonb,
   '["revolut.com/en-PL"]'::jsonb,
   NULL,
   'финансы',
   'service',
   'revolut.com/en-PL',
   '["no_pesel", "free", "multicurrency", "fully_online"]'::jsonb,
   '0 zł (Standard)',
   'Revolut',
   'A fintech neobank founded in London in 2015. It has no physical branches — everything happens through the app, and setting up an account takes just a few minutes. Over 70 million customers worldwide, a multi-currency account and a Visa/Mastercard card with interbank-rate currency exchange.',
   'Only through the Revolut mobile app (iOS/Android) or revolut.com — there are no bank offices or branches in Poland.',
   NULL,
   NULL,
   'Standard plan — 0 zł. Paid plans: Plus — 19.99 zł/month, Premium — 33.99 zł/month, Metal — 55.99 zł/month, Ultra — from 260 zł/month (introductory price).',
   'Sign-up takes a few minutes; document checks can take up to 5 business days.',
   NULL,
   'finance',
   '0 zł (Standard)',
   '["Passport or national ID card for EU/UK/Swiss citizens (valid for at least 1 month)", "For other nationalities — additionally a visa or residence card (valid for at least 3 months)", "For Ukrainian citizens — residence card, visa, Polish foreigner''s document, or tolerated-stay permit", "A selfie for in-app video verification — PESEL is not required"]'::jsonb,
   '["Download the Revolut app and sign up with your phone number", "Photograph your passport or ID card and complete video selfie verification", "Enter your address in Poland", "Get a virtual card instantly in the app; order a physical card separately for delivery by post"]'::jsonb,
   '["Trying to open an account on a tourist visa or student residence permit without extra documents — Revolut may not accept these"]'::jsonb,
   '["One of the most popular fintech banks in Europe — over 70 million customers worldwide", "A multi-currency account and a Visa/Mastercard card with favorable exchange rates", "The free plan limits fee-free cash withdrawals and currency exchange — a paid plan can pay off with heavy use"]'::jsonb,
   'Revolut',
   '2015-yilda Londonda asos solingan fintex-neobank. Jismoniy filiallari yo''q — hammasi ilova orqali amalga oshiriladi, hisob ochish bir necha daqiqa vaqt oladi. Butun dunyo bo''yicha 70 milliondan ortiq mijoz, ko''pvalyutali hisob va bank oraro kursda valyuta almashtiruvchi Visa/Mastercard karta.',
   'Faqat Revolut mobil ilovasi (iOS/Android) yoki revolut.com orqali — Polshada bank ofislari yoki filiallari yo''q.',
   NULL,
   NULL,
   'Standard tarifi — 0 zł. Pullik tariflar: Plus — 19,99 zł/oy, Premium — 33,99 zł/oy, Metal — 55,99 zł/oy, Ultra — 260 zł/oydan (boshlang''ich narx).',
   'Ro''yxatdan o''tish bir necha daqiqa, hujjatlarni tekshirish 5 ish kunigacha davom etishi mumkin.',
   NULL,
   'moliya',
   '0 zł (Standard)',
   '["YEI/Buyuk Britaniya/Shveytsariya fuqarosining pasporti yoki ID-kartasi (kamida 1 oy amal qiladigan)", "Boshqa mamlakat fuqarolari uchun — qo''shimcha ravishda viza yoki turar joy kartasi (kamida 3 oy amal qiladigan)", "Ukrainaliklar uchun — turar joy kartasi, viza, chet ellik uchun polyak hujjati yoki toleranslashtirilgan yashash ruxsatnomasi", "Ilovada video tasdiqlash uchun selfi — PESEL talab qilinmaydi"]'::jsonb,
   '["Revolut ilovasini yuklab oling va telefon raqamingiz bilan ro''yxatdan o''ting", "Pasport yoki ID-kartangizni suratga oling va video-selfi orqali tasdiqlashdan o''ting", "Polshadagi yashash manzilingizni kiriting", "Ilovada darhol virtual karta oling, jismoniy kartani esa alohida buyurtma qiling — pochta orqali yetkaziladi"]'::jsonb,
   '["Qo''shimcha hujjatlarsiz turistik viza yoki talaba turar joy ruxsatnomasi bilan hisob ochishga urinish — Revolut buni qabul qilmasligi mumkin"]'::jsonb,
   '["Yevropadagi eng mashhur fintex banklaridan biri — butun dunyo bo''yicha 70 milliondan ortiq mijoz", "Qulay kursda valyuta almashtiruvchi ko''pvalyutali hisob va Visa/Mastercard karta", "Bepul tarif komissiyasiz pul yechish va valyuta almashtirishni cheklaydi — faol foydalanishda pullik tarif foydaliroq bo''lishi mumkin"]'::jsonb,
   'Revolut',
   '2015 yılında Londra''da kurulan bir fintek neobank. Fiziksel şubesi yoktur — her şey uygulama üzerinden gerçekleşir, hesap açmak sadece birkaç dakika sürer. Dünya genelinde 70 milyondan fazla müşteri, çok para birimli hesap ve bankalar arası kurdan döviz bozdurma imkânı sunan Visa/Mastercard kart.',
   'Yalnızca Revolut mobil uygulaması (iOS/Android) veya revolut.com üzerinden — Polonya''da banka ofisi veya şubesi yoktur.',
   NULL,
   NULL,
   'Standard plan — 0 zł. Ücretli planlar: Plus — 19,99 zł/ay, Premium — 33,99 zł/ay, Metal — 55,99 zł/ay, Ultra — 260 zł/aydan itibaren (giriş fiyatı).',
   'Kayıt birkaç dakika sürer, belge kontrolü 5 iş gününe kadar sürebilir.',
   NULL,
   'finans',
   '0 zł (Standard)',
   '["AB/Birleşik Krallık/İsviçre vatandaşları için pasaport veya kimlik kartı (en az 1 ay geçerli)", "Diğer ülke vatandaşları için — ayrıca vize veya ikamet kartı (en az 3 ay geçerli)", "Ukraynalılar için — ikamet kartı, vize, Polonya yabancı belgesi veya tolere edilen ikamet izni", "Uygulama içi video doğrulama için selfie — PESEL gerekmez"]'::jsonb,
   '["Revolut uygulamasını indirin ve telefon numaranızla kaydolun", "Pasaportunuzu veya kimlik kartınızı fotoğraflayın ve video selfie doğrulamasını tamamlayın", "Polonya''daki adresinizi girin", "Uygulamada anında sanal kart alın; fiziksel kartı ayrıca sipariş edin — posta ile teslim edilir"]'::jsonb,
   '["Ek belge olmadan turist vizesi veya öğrenci ikamet izniyle hesap açmaya çalışmak — Revolut bunları kabul etmeyebilir"]'::jsonb,
   '["Avrupa''nın en popüler fintek bankalarından biri — dünya genelinde 70 milyondan fazla müşteri", "Avantajlı kurdan döviz bozdurma imkânı sunan çok para birimli hesap ve Visa/Mastercard kart", "Ücretsiz plan, komisyonsuz nakit çekme ve döviz bozdurmayı sınırlar — yoğun kullanımda ücretli plan daha avantajlı olabilir"]'::jsonb,
   'Revolut',
   'Необанки финтексӣ, ки соли 2015 дар Лондон таъсис ёфтааст. Филиали ҷисмонӣ надорад — ҳама кор тавассути барнома анҷом мешавад, кушодани ҳисоб якчанд дақиқа вақт мегирад. Зиёда аз 70 миллион мизоҷ дар саросари ҷаҳон, ҳисоби бисёрасъёра ва корти Visa/Mastercard бо мубодилаи асъор бо қурби байнибонкӣ.',
   'Танҳо тавассути барномаи мобилии Revolut (iOS/Android) ё сайти revolut.com — дар Полша офис ё филиали бонк вуҷуд надорад.',
   NULL,
   NULL,
   'Тарифи Standard — 0 zł. Тарифҳои пулакӣ: Plus — 19,99 zł/моҳ, Premium — 33,99 zł/моҳ, Metal — 55,99 zł/моҳ, Ultra — аз 260 zł/моҳ (нархи оғозӣ).',
   'Бақайдгирӣ якчанд дақиқа тӯл мекашад, санҷиши ҳуҷҷатҳо метавонад то 5 рӯзи корӣ давом кунад.',
   NULL,
   'молия',
   '0 zł (Standard)',
   '["Шиноснома ё корти шиносоии шаҳрванди ИА/Британияи Кабир/Швейтсария (аққал 1 моҳ эътибор дошта бошад)", "Барои шаҳрвандони дигар кишварҳо — иловатан виза ё корти иқомат (аққал 3 моҳ эътибор дошта бошад)", "Барои украинҳо — корти иқомат, виза, ҳуҷҷати хориҷии полякӣ ё иҷозати иқомати толерантӣ", "Селфӣ барои тасдиқи видеоӣ дар барнома — PESEL талаб карда намешавад"]'::jsonb,
   '["Барномаи Revolut-ро зеркашӣ кунед ва бо рақами телефон номнавис шавед", "Шинослнома ё корти шиносоии худро сурат гиред ва тасдиқи видео-селфиро анҷом диҳед", "Суроғаи истиқомати худро дар Полша нишон диҳед", "Дарҳол корти виртуалӣ дар барнома гиред, корти ҷисмониро алоҳида фармоиш диҳед — тавассути почта расонида мешавад"]'::jsonb,
   '["Кӯшиши кушодани ҳисоб бо визаи туристӣ ё иҷозати иқомати донишҷӯӣ бидуни ҳуҷҷатҳои иловагӣ — Revolut метавонад инро қабул накунад"]'::jsonb,
   '["Яке аз необанкҳои маъмултарини технологии молиявӣ дар Аврупо — зиёда аз 70 миллион мизоҷ дар саросари ҷаҳон", "Ҳисоби бисёрасъёра ва корти Visa/Mastercard бо мубодилаи асъор бо қурби муфид", "Тарифи ройгон бардошти пул ва мубодилаи асъорро бидуни комиссия маҳдуд мекунад — ҳангоми истифодаи фаъол тарифи пулакӣ метавонад муфидтар бошад"]'::jsonb,
   'Revolut',
   'Фінтех-необанк, заснований у 2015 році в Лондоні. Працює без жодного фізичного відділення, повністю через додаток — оформлення рахунку займає кілька хвилин. Понад 70 млн клієнтів по всьому світу, мультивалютний рахунок і картка Visa/Mastercard з обміном валют за міжбанківським курсом.',
   'Лише через мобільний додаток Revolut (iOS/Android) або сайт revolut.com — офісів і відділень банку в Польщі немає.',
   NULL,
   NULL,
   'План Standard — 0 zł. Платні плани: Plus — 19,99 zł/міс, Premium — 33,99 zł/міс, Metal — 55,99 zł/міс, Ultra — від 260 zł/міс (вступна ціна).',
   'Реєстрація — кілька хвилин, перевірка документів може тривати до 5 робочих днів.',
   NULL,
   'фінанси',
   '0 zł (Standard)',
   '["Паспорт або ID-картка громадянина ЄС/Великої Британії/Швейцарії (дійсні мінімум 1 місяць)", "Для громадян інших країн — додатково віза або карта побиту (дійсні мінімум 3 місяці)", "Для українців — карта побиту, віза, польський документ іноземця або дозвіл на толероване перебування", "Селфі для відеоверифікації в додатку — PESEL не потрібен"]'::jsonb,
   '["Завантажте додаток Revolut і зареєструйтеся за номером телефону", "Сфотографуйте паспорт або ID-картку та пройдіть відеоселфі-верифікацію", "Вкажіть адресу проживання в Польщі", "Отримайте віртуальну картку одразу в додатку, фізичну — замовте окремо з доставкою поштою"]'::jsonb,
   '["Намагатися відкрити рахунок за туристичною візою чи студентським видом на проживання без додаткових документів — Revolut може їх не прийняти"]'::jsonb,
   '["Один з найпопулярніших фінтех-банків у Європі — понад 70 млн клієнтів по всьому світу", "Мультивалютний рахунок і картка Visa/Mastercard з вигідним курсом обміну валют", "Безкоштовний план обмежує зняття готівки та обмін валют без комісії — за активного використання платний план може бути вигіднішим"]'::jsonb),
  ('Wise',
   'Финансовый онлайн-сервис для международных переводов и мультивалютных счетов, основан в 2011 году в Лондоне как TransferWise, переименован в Wise в 2021 году, акции торгуются на Лондонской бирже. Обслуживает более 10,9 млн активных клиентов по всему миру, позволяет держать и переводить деньги в 40+ валютах по межбанковскому курсу без скрытых наценок.',
   NULL,
   'Только через сайт wise.com или приложение Wise (iOS/Android) — физических отделений нет.',
   NULL,
   NULL,
   '["Паспорт или ID-карта", "Подтверждение адреса проживания (например, скан договора аренды или счёта за коммунальные услуги)", "PESEL не требуется"]'::jsonb,
   'Открытие и ведение счёта — бесплатно. Комиссия взимается только за конвертацию валют и переводы (обычно 0,3–2% в зависимости от валютной пары) и за разовый заказ карты.',
   'Обычно в течение одного дня после загрузки документов.',
   '["Зарегистрируйтесь на wise.com или в приложении по email, Google или Apple ID", "Загрузите фото паспорта или ID-карты и подтверждение адреса", "Дождитесь проверки документов", "При желании закажите мультивалютную карту Wise — она доставляется по почте"]'::jsonb,
   '["Комиссия за перевод зависит от способа оплаты — переводом с банковского счёта обычно дешевле, чем картой, сравнивайте способы перед отправкой"]'::jsonb,
   '["Особенно удобен для переводов из-за рубежа и хранения нескольких валют одновременно", "Курс обмена — межбанковский, без скрытой наценки, обычно выгоднее классических банковских переводов", "Мультивалютная карта Wise позволяет тратить деньги за границей без комиссии за конвертацию в поддерживаемых валютах"]'::jsonb,
   '["wise.com"]'::jsonb,
   NULL,
   'финансы',
   'service',
   'wise.com',
   '["no_pesel", "free", "multicurrency", "fully_online"]'::jsonb,
   '0 zł, платите только за конвертацию',
   'Wise',
   'An online financial service for international transfers and multi-currency accounts, founded in London in 2011 as TransferWise and renamed Wise in 2021; its shares trade on the London Stock Exchange. It serves over 10.9 million active customers worldwide and lets you hold and send money in 40+ currencies at the interbank rate with no hidden markup.',
   'Only through wise.com or the Wise app (iOS/Android) — there are no physical branches.',
   NULL,
   NULL,
   'Opening and maintaining an account is free. Fees apply only to currency conversion and transfers (typically 0.3–2% depending on the currency pair) and a one-off card order fee.',
   'Usually within one day of uploading your documents.',
   NULL,
   'finance',
   '0 zł, you only pay for conversion',
   '["Passport or national ID card", "Proof of address (e.g. a scan of a rental agreement or a utility bill)", "PESEL is not required"]'::jsonb,
   '["Sign up at wise.com or in the app with your email, Google, or Apple ID", "Upload a photo of your passport or ID card and proof of address", "Wait for document verification", "Optionally order the multi-currency Wise card — it''s delivered by post"]'::jsonb,
   '["Transfer fees depend on the payment method — a bank transfer is usually cheaper than a card payment, so compare methods before sending"]'::jsonb,
   '["Especially convenient for receiving transfers from abroad and holding several currencies at once", "The exchange rate is the interbank rate with no hidden markup, usually cheaper than a classic bank transfer", "The Wise multi-currency card lets you spend abroad with no conversion fee in supported currencies"]'::jsonb,
   'Wise',
   'Xalqaro o''tkazmalar va ko''pvalyutali hisoblar uchun onlayn moliyaviy xizmat, 2011-yilda Londonda TransferWise nomi bilan asos solingan, 2021-yilda Wise deb qayta nomlangan; aksiyalari London fond birjasida savdo qilinadi. Butun dunyo bo''yicha 10,9 milliondan ortiq faol mijozga xizmat ko''rsatadi, 40 dan ortiq valyutada pulni bank oraro kursda, yashirin ustama to''lovsiz saqlash va jo''natish imkonini beradi.',
   'Faqat wise.com sayti yoki Wise ilovasi (iOS/Android) orqali — jismoniy filiallar yo''q.',
   NULL,
   NULL,
   'Hisobni ochish va yuritish — bepul. To''lov faqat valyuta konvertatsiyasi va o''tkazmalar uchun olinadi (odatda valyuta juftligiga qarab 0,3–2%) hamda kartani bir martalik buyurtma qilish uchun.',
   'Odatda hujjatlarni yuklagandan keyin bir kun ichida.',
   NULL,
   'moliya',
   '0 zł, faqat konvertatsiya uchun to''laysiz',
   '["Pasport yoki ID-karta", "Yashash manzilini tasdiqlovchi hujjat (masalan, ijara shartnomasi yoki kommunal to''lov cheki skani)", "PESEL talab qilinmaydi"]'::jsonb,
   '["wise.com saytida yoki ilovada email, Google yoki Apple ID orqali ro''yxatdan o''ting", "Pasport yoki ID-karta suratini va manzilni tasdiqlovchi hujjatni yuklang", "Hujjatlar tekshiruvini kuting", "Xohishga ko''ra ko''pvalyutali Wise kartasini buyurtma qiling — u pochta orqali yetkaziladi"]'::jsonb,
   '["O''tkazma komissiyasi to''lov usuliga bog''liq — bank hisobidan o''tkazish odatda kartadan arzonroq, yuborishdan oldin usullarni solishtiring"]'::jsonb,
   '["Chet eldan o''tkazmalar qabul qilish va bir vaqtning o''zida bir nechta valyutani saqlash uchun ayniqsa qulay", "Almashuv kursi — yashirin ustamasiz bank oraro kurs, odatda klassik bank o''tkazmalaridan arzonroq", "Wise ko''pvalyutali kartasi qo''llab-quvvatlanadigan valyutalarda chet elda konvertatsiya komissiyasisiz xarajat qilish imkonini beradi"]'::jsonb,
   'Wise',
   'Uluslararası transferler ve çok para birimli hesaplar için çevrimiçi finansal hizmet; 2011 yılında Londra''da TransferWise adıyla kurulmuş, 2021''de Wise olarak yeniden adlandırılmıştır; hisseleri Londra Menkul Kıymetler Borsası''nda işlem görür. Dünya genelinde 10,9 milyondan fazla aktif müşteriye hizmet verir, 40''tan fazla para biriminde bankalar arası kurdan, gizli ek ücret olmadan para tutma ve gönderme imkânı sunar.',
   'Yalnızca wise.com veya Wise uygulaması (iOS/Android) üzerinden — fiziksel şube yoktur.',
   NULL,
   NULL,
   'Hesap açma ve işletme ücretsizdir. Ücret yalnızca döviz dönüşümü ve transferler için alınır (genellikle para birimi çiftine bağlı olarak %0,3–2) ve tek seferlik kart sipariş ücreti vardır.',
   'Genellikle belgeler yüklendikten sonra bir gün içinde.',
   NULL,
   'finans',
   '0 zł, yalnızca dönüşüm için ödeme yaparsınız',
   '["Pasaport veya kimlik kartı", "İkamet adresi kanıtı (örn. kira sözleşmesi veya fatura taraması)", "PESEL gerekmez"]'::jsonb,
   '["wise.com''da veya uygulamada e-posta, Google veya Apple ID ile kaydolun", "Pasaport veya kimlik kartı fotoğrafınızı ve adres kanıtınızı yükleyin", "Belge doğrulamasını bekleyin", "İsterseniz çok para birimli Wise kartını sipariş edin — posta ile teslim edilir"]'::jsonb,
   '["Transfer ücreti ödeme yöntemine bağlıdır — banka hesabından transfer genellikle karttan daha ucuzdur, göndermeden önce yöntemleri karşılaştırın"]'::jsonb,
   '["Yurt dışından transfer almak ve aynı anda birden fazla para birimini tutmak için özellikle kullanışlıdır", "Döviz kuru, gizli ek ücret olmadan bankalar arası kurdur, genellikle klasik banka transferinden daha ucuzdur", "Wise çok para birimli kartı, desteklenen para birimlerinde yurt dışında dönüşüm ücreti olmadan harcama yapmanızı sağlar"]'::jsonb,
   'Wise',
   'Хизмати молиявии онлайн барои интиқолҳои байналмилалӣ ва ҳисобҳои бисёрасъёра, ки соли 2011 дар Лондон бо номи TransferWise таъсис ёфта, соли 2021 ба Wise иваз карда шудааст; саҳмияҳояш дар Биржаи фондии Лондон муомила мешаванд. Зиёда аз 10,9 миллион мизоҷи фаъолро дар саросари ҷаҳон хидмат мерасонад ва имкон медиҳад пулро дар зиёда аз 40 асъор бо қурби байнибонкӣ, бидуни иловапулии пинҳонӣ нигоҳ доред ва фиристед.',
   'Танҳо тавассути сайти wise.com ё барномаи Wise (iOS/Android) — филиали ҷисмонӣ вуҷуд надорад.',
   NULL,
   NULL,
   'Кушодан ва нигоҳдории ҳисоб — ройгон. Комиссия танҳо барои мубодилаи асъор ва интиқолҳо гирифта мешавад (одатан 0,3–2% вобаста ба ҷуфти асъор) ва барои фармоиши якдафъаинаи корт.',
   'Одатан дар давоми як рӯз пас аз боргузории ҳуҷҷатҳо.',
   NULL,
   'молия',
   '0 zł, танҳо барои мубодила пардохт мекунед',
   '["Шиноснома ё корти шиносоӣ", "Исботи суроғаи истиқомат (масалан, сканери шартномаи иҷора ё квитансияи хизматрасониҳои коммуналӣ)", "PESEL талаб карда намешавад"]'::jsonb,
   '["Дар wise.com ё дар барнома тавассути почтаи электронӣ, Google ё Apple ID номнавис шавед", "Сурати шиноснома ё корти шиносоӣ ва исботи суроғаро боргузорӣ кунед", "Санҷиши ҳуҷҷатҳоро интизор шавед", "Хоҳиш кунед, корти бисёрасъёраи Wise-ро фармоиш диҳед — он тавассути почта расонида мешавад"]'::jsonb,
   '["Комиссияи интиқол ба усули пардохт вобаста аст — интиқол аз ҳисоби бонкӣ одатан аз корт арзонтар аст, пеш аз фиристодан усулҳоро муқоиса кунед"]'::jsonb,
   '["Барои қабули интиқолҳо аз хориҷа ва нигоҳ доштани якчанд асъор дар як вақт хеле мувофиқ аст", "Қурби мубодила — қурби байнибонкӣ бидуни иловапулии пинҳонӣ, одатан аз интиқоли бонкии классикӣ арзонтар", "Корти бисёрасъёраи Wise имкон медиҳад дар хориҷа бидуни комиссияи мубодила дар асъорҳои дастгиришаванда харҷ кунед"]'::jsonb,
   'Wise',
   'Онлайн-фінансовий сервіс для міжнародних переказів і мультивалютних рахунків, заснований у Лондоні в 2011 році як TransferWise, перейменований на Wise у 2021 році; акції торгуються на Лондонській біржі. Обслуговує понад 10,9 млн активних клієнтів по всьому світу, дозволяє тримати і переказувати гроші в 40+ валютах за міжбанківським курсом без прихованих націнок.',
   'Лише через сайт wise.com або додаток Wise (iOS/Android) — фізичних відділень немає.',
   NULL,
   NULL,
   'Відкриття та ведення рахунку — безкоштовно. Комісія стягується лише за конвертацію валют і перекази (зазвичай 0,3–2% залежно від валютної пари) та за разове замовлення картки.',
   'Зазвичай протягом одного дня після завантаження документів.',
   NULL,
   'фінанси',
   '0 zł, платите лише за конвертацію',
   '["Паспорт або ID-картка", "Підтвердження адреси проживання (наприклад, скан договору оренди або рахунку за комунальні послуги)", "PESEL не потрібен"]'::jsonb,
   '["Зареєструйтеся на wise.com або в додатку через email, Google чи Apple ID", "Завантажте фото паспорта або ID-картки та підтвердження адреси", "Дочекайтеся перевірки документів", "За бажанням замовте мультивалютну картку Wise — вона доставляється поштою"]'::jsonb,
   '["Комісія за переказ залежить від способу оплати — переказ з банківського рахунку зазвичай дешевший за оплату карткою, порівнюйте способи перед відправленням"]'::jsonb,
   '["Особливо зручний для отримання переказів з-за кордону та зберігання кількох валют одночасно", "Курс обміну — міжбанківський, без прихованої націнки, зазвичай вигідніше класичних банківських переказів", "Мультивалютна картка Wise дозволяє витрачати гроші за кордоном без комісії за конвертацію в підтримуваних валютах"]'::jsonb),
  ('N26',
   'Немецкий онлайн-банк с полноценной банковской лицензией BaFin, основан в 2013 году в Берлине. Доступен резидентам Польши — свыше 4,8 млн клиентов по всему миру, полностью дистанционное открытие счёта через приложение с видеоидентификацией.',
   NULL,
   'Только через приложение N26 (iOS/Android) — отделений в Польше нет.',
   NULL,
   NULL,
   '["Паспорт или ID-карта", "Смартфон с камерой для видеоидентификации личности", "PESEL не требуется"]'::jsonb,
   'Базовый счёт N26 Standard — бесплатно. Платные тарифы Smart, You, Metal — от нескольких евро в месяц.',
   'Видеоверификация обычно занимает 5–10 минут, карта доставляется по почте в течение нескольких дней.',
   '["Скачайте приложение N26 и укажите email и номер телефона", "Пройдите видеоидентификацию личности с паспортом или ID-картой", "Укажите адрес — можно указать адрес проживания в Польше", "Дождитесь карты Mastercard по почте"]'::jsonb,
   '["Превышение бесплатного лимита снятия наличных или снятие в валюте, отличной от евро — уточняйте лимиты в приложении, чтобы не платить комиссию"]'::jsonb,
   '["Быстрое открытие счёта прямо в приложении — обычно занимает не больше 10 минут", "3–5 бесплатных снятий наличных в банкоматах ЕС в месяц", "Поддержка доступна на английском, немецком, французском, испанском и итальянском языках"]'::jsonb,
   '["n26.com/en-eu"]'::jsonb,
   NULL,
   'финансы',
   'service',
   'n26.com/en-eu',
   '["no_pesel", "free"]'::jsonb,
   '0 zł (Standard, счёт в EUR)',
   'N26',
   'A German online bank with a full BaFin banking licence, founded in Berlin in 2013. Available to residents of Poland — over 4.8 million customers worldwide, with fully remote account opening through the app via video identification.',
   'Only through the N26 app (iOS/Android) — there are no branches in Poland.',
   NULL,
   NULL,
   'The basic N26 Standard account is free. Paid Smart, You, and Metal plans start from a few euros per month.',
   'Video verification usually takes 5–10 minutes; the card arrives by post within a few days.',
   NULL,
   'finance',
   '0 zł (Standard, EUR account)',
   '["Passport or national ID card", "A smartphone with a camera for video identity verification", "PESEL is not required"]'::jsonb,
   '["Download the N26 app and enter your email and phone number", "Complete video identity verification with your passport or ID card", "Enter your address — a Polish residential address is fine", "Wait for your Mastercard to arrive by post"]'::jsonb,
   '["Exceeding the free cash withdrawal limit or withdrawing in a currency other than euro — check the limits in the app to avoid fees"]'::jsonb,
   '["Fast account opening right in the app — usually takes no more than 10 minutes", "3–5 free cash withdrawals a month at EU ATMs", "Support is available in English, German, French, Spanish, and Italian"]'::jsonb,
   'N26',
   'To''liq BaFin bank litsenziyasiga ega nemis onlayn banki, 2013-yilda Berlinda asos solingan. Polsha rezidentlariga ochiq — butun dunyo bo''yicha 4,8 milliondan ortiq mijoz, ilova orqali video tasdiqlash bilan to''liq masofaviy hisob ochish.',
   'Faqat N26 ilovasi (iOS/Android) orqali — Polshada filiallar yo''q.',
   NULL,
   NULL,
   'Asosiy N26 Standard hisobi — bepul. Pullik Smart, You, Metal tariflari oyiga bir necha yevrodan boshlanadi.',
   'Video tasdiqlash odatda 5–10 daqiqa davom etadi, karta bir necha kun ichida pochta orqali yetkaziladi.',
   NULL,
   'moliya',
   '0 zł (Standard, EUR hisobi)',
   '["Pasport yoki ID-karta", "Video orqali shaxsni tasdiqlash uchun kamerali smartfon", "PESEL talab qilinmaydi"]'::jsonb,
   '["N26 ilovasini yuklab oling va email va telefon raqamingizni kiriting", "Pasport yoki ID-karta bilan video orqali shaxsingizni tasdiqlang", "Manzilingizni kiriting — Polshadagi yashash manzilini ko''rsatish mumkin", "Mastercard kartangiz pochta orqali kelishini kuting"]'::jsonb,
   '["Bepul pul yechish limitidan oshib ketish yoki yevrodan boshqa valyutada pul yechish — komissiya to''lamaslik uchun ilovada limitlarni tekshiring"]'::jsonb,
   '["Ilovada tez hisob ochish — odatda 10 daqiqadan ko''p vaqt olmaydi", "YEI bankomatlarida oyiga 3–5 marta bepul pul yechish", "Qo''llab-quvvatlash xizmati ingliz, nemis, fransuz, ispan va italyan tillarida mavjud"]'::jsonb,
   'N26',
   'Tam BaFin bankacılık lisansına sahip Alman online bankası, 2013 yılında Berlin''de kuruldu. Polonya sakinlerine açık — dünya genelinde 4,8 milyondan fazla müşteri, uygulama üzerinden video kimlik doğrulamasıyla tamamen uzaktan hesap açma.',
   'Yalnızca N26 uygulaması (iOS/Android) üzerinden — Polonya''da şube yoktur.',
   NULL,
   NULL,
   'Temel N26 Standard hesabı ücretsizdir. Ücretli Smart, You, Metal planları aylık birkaç eurodan başlar.',
   'Video doğrulama genellikle 5–10 dakika sürer, kart birkaç gün içinde posta ile gelir.',
   NULL,
   'finans',
   '0 zł (Standard, EUR hesap)',
   '["Pasaport veya kimlik kartı", "Video kimlik doğrulaması için kameralı akıllı telefon", "PESEL gerekmez"]'::jsonb,
   '["N26 uygulamasını indirin ve e-posta ile telefon numaranızı girin", "Pasaport veya kimlik kartınızla video kimlik doğrulamasını tamamlayın", "Adresinizi girin — Polonya''daki ikamet adresinizi belirtebilirsiniz", "Mastercard''ınızın posta ile gelmesini bekleyin"]'::jsonb,
   '["Ücretsiz nakit çekme limitini aşmak veya euro dışında bir para biriminde çekim yapmak — ücretlerden kaçınmak için uygulamadaki limitleri kontrol edin"]'::jsonb,
   '["Uygulama üzerinden hızlı hesap açma — genellikle 10 dakikadan fazla sürmez", "AB ATM''lerinde ayda 3–5 ücretsiz nakit çekme", "Destek İngilizce, Almanca, Fransızca, İspanyolca ve İtalyanca dillerinde sunulur"]'::jsonb,
   'N26',
   'Бонки онлайни олмонӣ бо литсензияи пурраи бонкии BaFin, ки соли 2013 дар Берлин таъсис ёфтааст. Барои сокинони Полша дастрас аст — зиёда аз 4,8 миллион мизоҷ дар саросари ҷаҳон, кушодани ҳисоби комилан дурдаст тавассути барнома бо тасдиқи видеоӣ.',
   'Танҳо тавассути барномаи N26 (iOS/Android) — дар Полша филиал вуҷуд надорад.',
   NULL,
   NULL,
   'Ҳисоби асосии N26 Standard — ройгон. Тарифҳои пулакии Smart, You, Metal аз якчанд евро дар моҳ оғоз мешаванд.',
   'Тасдиқи видеоӣ одатан 5–10 дақиқа тӯл мекашад, корт дар давоми якчанд рӯз тавассути почта мерасад.',
   NULL,
   'молия',
   '0 zł (Standard, ҳисоби EUR)',
   '["Шиноснома ё корти шиносоӣ", "Смартфон бо камера барои тасдиқи видеоии шахсият", "PESEL талаб карда намешавад"]'::jsonb,
   '["Барномаи N26-ро зеркашӣ кунед ва почтаи электронӣ ва рақами телефони худро нишон диҳед", "Тасдиқи видеоии шахсиятро бо шиноснома ё корти шиносоӣ анҷом диҳед", "Суроғаи худро нишон диҳед — суроғаи истиқомат дар Полша қобили қабул аст", "Расидани корти Mastercard тавассути почтаро интизор шавед"]'::jsonb,
   '["Аз ҳадди бардошти пули ройгон гузаштан ё бардошти пул бо асъори ғайр аз евро — барои пардохт накардани комиссия ҳадҳоро дар барнома санҷед"]'::jsonb,
   '["Кушодани ҳисоби зуд мустақиман дар барнома — одатан на бештар аз 10 дақиқа тӯл мекашад", "3–5 бардошти пули нақди ройгон дар банкоматҳои ИА дар як моҳ", "Дастгирӣ бо забонҳои англисӣ, олмонӣ, фаронсавӣ, испанӣ ва итолиёвӣ дастрас аст"]'::jsonb,
   'N26',
   'Німецький онлайн-банк із повноцінною банківською ліцензією BaFin, заснований у 2013 році в Берліні. Доступний резидентам Польщі — понад 4,8 млн клієнтів по всьому світу, повністю дистанційне відкриття рахунку через додаток із відеоідентифікацією.',
   'Лише через додаток N26 (iOS/Android) — відділень у Польщі немає.',
   NULL,
   NULL,
   'Базовий рахунок N26 Standard — безкоштовно. Платні тарифи Smart, You, Metal — від кількох євро на місяць.',
   'Відеоверифікація зазвичай триває 5–10 хвилин, картка доставляється поштою протягом кількох днів.',
   NULL,
   'фінанси',
   '0 zł (Standard, рахунок у EUR)',
   '["Паспорт або ID-картка", "Смартфон із камерою для відеоідентифікації особи", "PESEL не потрібен"]'::jsonb,
   '["Завантажте додаток N26 і вкажіть email та номер телефону", "Пройдіть відеоідентифікацію особи з паспортом або ID-карткою", "Вкажіть адресу — можна вказати адресу проживання в Польщі", "Дочекайтеся картки Mastercard поштою"]'::jsonb,
   '["Перевищення безкоштовного ліміту зняття готівки або зняття у валюті, відмінній від євро — перевіряйте ліміти в додатку, щоб не платити комісію"]'::jsonb,
   '["Швидке відкриття рахунку прямо в додатку — зазвичай займає не більше 10 хвилин", "3–5 безкоштовних знять готівки в банкоматах ЄС на місяць", "Підтримка доступна англійською, німецькою, французькою, іспанською та італійською мовами"]'::jsonb);
